# Generated by Django 2.0.7 on 2020-06-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='video/', verbose_name=''),
        ),
    ]
