# Generated by Django 3.0.6 on 2020-05-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0002_auto_20200521_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadcsv',
            name='id',
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='nim',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
