# Generated by Django 3.0.6 on 2020-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0003_auto_20200522_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='jadwal',
            field=models.IntegerField(default=0),
        ),
    ]
