# Generated by Django 3.0.6 on 2020-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0004_profil_jadwal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='jadwal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
