# Generated by Django 3.0.6 on 2020-06-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0005_auto_20200605_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='video/', verbose_name=''),
        ),
    ]
