# Generated by Django 3.0.6 on 2020-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0006_auto_20200610_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertemuan',
            name='simpan',
            field=models.BooleanField(default=0),
        ),
    ]
