# Generated by Django 3.0.6 on 2020-06-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0007_pertemuan_simpan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertemuan',
            name='simpan',
            field=models.NullBooleanField(default=0),
        ),
    ]
