# Generated by Django 3.0.6 on 2020-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0008_auto_20200610_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertemuan',
            name='simpan',
            field=models.BooleanField(default=0),
        ),
    ]
