# Generated by Django 3.0.6 on 2020-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0009_auto_20200611_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='jadwal',
            field=models.TimeField(),
        ),
    ]
