# Generated by Django 3.0.6 on 2020-06-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0011_remove_video_deskripsi_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='deskripsi_video',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
