# Generated by Django 3.0.6 on 2020-06-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0012_video_deskripsi_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='deskripsi_video',
        ),
    ]
