# Generated by Django 3.0.6 on 2020-06-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0013_remove_video_deskripsi_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertemuan',
            name='tanggal_perkuliahan',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pertemuan',
            name='waktu_perkuliahan',
            field=models.TimeField(auto_now=True),
        ),
    ]
