# Generated by Django 3.0.6 on 2020-06-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0016_filekehadiran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filekehadiran',
            name='deskripsi_file',
        ),
    ]
